language: node_js
node_js:
- 4.0
- 6.0
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
before_install:
- npm install -g mocha
deploy:
- provider: script    # (If version.txt is updated) - create a new tag and push to Github, update the latest-release branch
  script: ./create-release.sh
  on: master
  # Automatic deploys are enabled in Heroku for this app
  # Every push to master will deploy a new version of this app. Deploys happen automatically.
  # Heroku will wait for CI to pass before deploying.
notifications:
  email: false
sudo: false
env:
  global:
  - secure: esj3ut+TwKX25QzU1koJyTVIX+x1V55graI65X8LiYXKcOP040VPJ9lIC0HeRs5UViBM0Ur1F93rGdgW2zYVzu5MLZoH7KjpzMcG30x+FDqLChT0JfNcLLtLm/wIhx/OAAmsBxXlvjPp092BeEKd3Jug8d329TxwwK5G5XxAatg=
