language: node_js
node_js:
  - 4.0
before_install:
  - npm install -g grunt-cli
install:
  - npm install
script:
  # Reference the locally-installed version of Grunt
  - ./node_modules/grunt-cli/bin/grunt test
after_success:
  # Check to see if the version file has been updated
  - ./create-release-tag.sh
deploy:
  provider: heroku
  api_key:
    secure: h/9/Rcd41XVU4VYYeBoKKvG6uShEoDksCGGZ/2dgeY1f3tYnhGzzgL6TIkvhafwDbKk2Y4o6d/MI05K+s7lorf2uTKpr1To2o52hQqmb4YREPWruZtBqoRo5X4nCeN2oEdW+yJRH3jZDNUmwkPzjytqxkcUUUeDPHfz3+xCtSZk=
  app: govuk-prototype-kit
  on: master

notifications:
  email: false

sudo: false
